apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deletemes.example.com
spec:
  group: example.com
  names:
    kind: DeleteMe
    listKind: DeleteMeList
    plural: deletemes
    singular: deleteme
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
